### ISSUE TITLE
gesture support not working

### ISSUE THREAD

**Issue by chetski** [MurhafSousli/ng-gallery#16]
I've used this library with angular 4.x and included hammerjs but the gesture support isn't working. My assumption would be that I would be able to swipe left/right on tablet/mobile devices but I've tried on ipad/iphone. I assumed it was my app but I've also tried it with the demo provided and both the basic and modal versions show the same problem/behaviour.

Am i mis-understanding the gesture support or is there anything specific to do once hammerjs is included?

ps. this is my GalleryConfig (note the "gestures: true" at the end)....

export const galleryConfig: GalleryConfig = {
  style: {
    background: '#121519',
    width: '1200px',
    height: '900px'
  },
  animation: 'fade',
  loader: {
    width: '50px',
    height: '50px',
    position: 'center',
    icon: 'oval'
  },
  description: {
    position: 'bottom',
    overlay: false,
    text: true,
    counter: true
  },
  bullets: false,
  player: {
    autoplay: false,
    speed: 3000
  },
  thumbnails: false,
  navigation: true,
  gestures: true
};

**Comment by MurhafSousli** [comment]
Swiping cannot work when `navigation` is enabled on large screens  (including ipad, tablet and mobile landscape), because it is being blocked by the navigation layer. disable it `navigation: false`

but on mobile, the navigation disappears out of the box, I used your config with the demo

![ezgif com-resize](https://user-images.githubusercontent.com/8130692/26841375-f8db5be6-4af1-11e7-8187-0dc8834dab75.gif)

**Comment by maku** [comment]
@MurhafSousli I tried the demo app on my mobile phone (iphone) and swiping does not work....

**Comment by MurhafSousli** [comment]
@maku which iphone and browser are you using?

**Comment by maku** [comment]
@MurhafSousli Sorry incorrect info -> it works (chrome and safari) - Only on IPad it does not work...

**Comment by MurhafSousli** [comment]
@maku As I told you in the [comment above](https://github.com/MurhafSousli/ng-gallery/issues/16#issuecomment-306550312), the navigation is blocking the gestures, disable it and it will work

**Comment by maku** [comment]
@MurhafSousli  Sorry I don't want to be annoying but I don't get the logical reason. By disabling the navigation area I have no buttons anymore.  And on Desktop all three navigation forms work (a kind of mouse swiping, click on button, click on left or right area). Why should this not be possible on tablets etc.. When I understand you right the navigation layer is part of your component.... So you have the control over this and which gestures are executed, right?

**Comment by MurhafSousli** [comment]
The navigation buttons makes the modal just like facebook photos modal.

Technically only one can work, because the navigation will be on top on the gestures layer, so you can't swipe.

> And on Desktop all three navigation forms work (a kind of mouse swiping, click on button, click on left or right area).

There is no difference between the desktop and the tablet.
The navigation component covers only the image, it does not cover the thumbnails. Therefore, gestures is not blocked on thumbnails.

**Comment by Codeonkey** [comment]
@MurhafSousli is your comments here still valid, we are trying the package, but on desktop, swiping does not work, but in the example you showcase on your page, swiping and navigation works together? 

https://ngx-gallery.netlify.app/#/gallery

We have hammerjs imported in the polyfill file, what are we missing?

**Comment by MurhafSousli** [comment]
@Codeonkey This thread is too old, Please open an issue with a reproduction stackblitz.
