### ISSUE TITLE
Disabling keyboard navigation (and input listening)

### ISSUE THREAD

**Issue by JakubEsterka** [MurhafSousli/ng-gallery#33]
Ive got very obnoxious problem - I need the gallery modal at the app.component and because it constantly listens to keyboard inputs, every time user presses ENTER (or other keys) modal window opens.

Is there any way how to solve this or rather how to disable keyboard navigation all together?

Thanks

**Comment by stankuhn** [comment]
Exactly.. This is a major issue. It actually doesn't matter where the gallery is included. Its an issue on the page where it is present. It constantly captures key inputs. At some point if gallery is empty it even yells errors in console.
Key inputs should be always ignored if gallery is not open.
Will you fix this please?
Otherwise very nice module guys.

**Comment by MurhafSousli** [comment]
@JakubEsterka @stankuhn I am currently working on the next update, and I will fix this for sure!
