### ISSUE TITLE
How to combine between <gallery> and lightbox modal.

### ISSUE THREAD

**Issue by sayeko** [MurhafSousli/ng-gallery#37]
Hey great implementation for gallery in ng,
I'm trying to figure out how to create <gallery></gallery> basic component to be on customize configuration and when I click on one of the images it will open the lightbox modal with another set of configuration.

thanks.

**Comment by MurhafSousli** [comment]
Hi @sayeko Did you read the docs, what have you tried?

**Comment by sayeko** [comment]
Yes of course I read the docs moreover the docs are not fully sync with the current version.
Anyway I'm trying to create a basic gallery each picture at a time, and when I press on the image it will open a lightbox modal gallery with the current image.
Currently behavior is when you click on the image it's just slide to next one.

**Comment by MurhafSousli** [comment]
@sayeko Do you mean that you want to open the lightbox when you click on an image inside the basic gallery?

**Comment by sayeko** [comment]
Hey thanks for quick response,
If I cancel the navigation from the config I would not be able to navigation inside the modal as well I think.
Do you plan for the next changes to add the ability to set different configuration for both state? lightbox or basic?, it would be the right way of thinking.

**Comment by MurhafSousli** [comment]
@sayeko Your use case is kinda odd. **ng-gallery** is still a young project, and it was made be a singleton to ease the usage.

The problem here is that all the galleries are synced with one state/config, so changing the config will reflect on both the basic element and the lightbox.

Ofcourse, it would be great to have multiple instances with different config, but this will complicate the usage, _we can discuss that_.

But for now try this
```html
<div class="my-basic-gallery">
    <gallery (click)="gallery.open(gallery.state.currIndex)"></gallery>
</div>
```
disable the navigation on the basic gallery using css
```css
.my-basic-gallery {
   gallery-nav {
       display: none !important;
   }
}
```
you can also add click event to the img element manually, instead of the solution above
```ts
this.renderer.listen(document.querySelector('.g-item img'), 'click', () => {
   this.gallery.open(this.gallery.currIndex);
});
```

**Comment by bastienlemaitre** [comment]
Can you explain how to combine <gallery> and lightbox modal with your new version ?

**Comment by bastienlemaitre** [comment]
I want to open Lightbox when i click on gallery. More useful with smartphone !
