### ISSUE TITLE
Error resolving ngfactory with AOT/rollup

### ISSUE THREAD

**Issue by clarkd** [MurhafSousli/ng-gallery#40]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows 10

### Versions
node: 9.0.0
npm: 5.5.1
angular: 4.4.4

### Repro steps
I'm unable to use this library with an AOT & Rollup configuration. I see the below error when the project is built with rollup. The angular compilation step (ngc) occurs without errors.

### The log given by the failure
```
events.js:193
      throw er; // Unhandled 'error' event
      ^
Error: Could not resolve '../../../../node_modules/ng-gallery/ng-gallery.ngfactory' from temp\aot\TypeScript\Core\app.module.ngfactory.js
    at error (C:\Users\Dave\Documents\Code Repository\dashboards.squaredup.com\UmbracoCommunity.Core\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:185:14)
    at then.resolvedId (C:\Users\Dave\Documents\Code Repository\dashboards.squaredup.com\UmbracoCommunity.Core\node_modules\rollup-stream\node_modules\rollup\dist\rollup.js:9804:8)
    at <anonymous>
Process terminated with code 1.
```

### Desired functionality
The library to work with aot (and rollup)! :)

**Comment by MurhafSousli** [comment]
Hi @clarkd, I am aware of this, there is a problem with ngc and angular CDK. It could be caused by the [building environments](https://github.com/tinesoft/generator-ngx-library), this is why the package is still beta, I am having difficulties detecting the cause at the moment. contribution on debugging this issue is very welcomed

For now If you want to use the gallery in AOT. download and include the source files (typescript) in your project instead of importing it from `node_modules` until we figure this out

**Comment by clarkd** [comment]
It looks like that the ngfactory files that are generated are typescript files which breaks Rollup because it'll be looking for JS files. Does that make sense?

I'm happy to take a look at your build setup but could you provide some more info/step on how you build & publish?

Thanks for the workaround, I'll give that a try!

**Comment by MurhafSousli** [comment]
@clarkd I am not sure! I am using the [ngx-library](https://github.com/tinesoft/generator-ngx-library) for the build setup, use `gulp build` to build, the dev process is explained in detail in the repo page.

I got to update the building environment with latest (maybe it solves the problem), it is frustrating. I am spending a lot time debugging these kind of issues, more than developing the module itself.

**Comment by clarkd** [comment]
There's been lots of changes with the ngc compiler etc. in the past few months so I wouldn't be surprised if updating the build setup to the latest versions etc. would fix the issues!

**Comment by MurhafSousli** [comment]
I can confirm now the the issue is caused by the current build setup, I will use this [generator](https://github.com/jvandemo/generator-angular2-library) once it support angular 5 in https://github.com/jvandemo/generator-angular2-library/issues/238

**Comment by maku** [comment]
@MurhafSousli seems https://github.com/jvandemo/generator-angular2-library/issues/238 is resolved :-)

**Comment by MurhafSousli** [comment]
@maku I see, I am working on it

**Comment by maku** [comment]
@MurhafSousli great, thank you very much

**Comment by sten82** [comment]
@clarkd @MurhafSousli 

I had the same issue. When I tried to build my application with aot I got that error:

`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\project\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
`

After some research I was able to I was able to find out how to get a better error message, because this message is so generic it could be everything. So I did:

`npm install enhanced-resolve@3.3.0`

On next aot build I got a better error message:

`ERROR in ./src/$$_gendir/node_modules/ng-gallery/ng-gallery.ngfactory.ts
Module not found: Error: Can't resolve 'ng-gallery/models/index' in 'C:\project\src\$$_gendir\node
 @ ./src/$$_gendir/node_modules/ng-gallery/ng-gallery.ngfactory.ts 7:0-873
 @ ./src/$$_gendir/app/gallery/gallery.module.ngfactory.ts
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
`

I solved that issue by adding index.ts in model folder as it had a problem when there are only index.d.ts - Now I'm able to do a aot production build.
